//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.HoaDon_SanPham = new HashSet<HoaDon_SanPham>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdKhachHang { get; set; }
        public string Ma { get; set; }
        public string GhiChu { get; set; }
        public long TongTien { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<HoaDon_SanPham> HoaDon_SanPham { get; set; }
    }
}
