//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public int Id { get; set; }
        public int IdGroup { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual KhachHangGroup KhachHangGroup { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
