//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDieuTri_Thuoc
    {
        public int Id { get; set; }
        public int IdPhieuDieuTri { get; set; }
        public int IdThuoc { get; set; }
        public double LieuLuong { get; set; }
    
        public virtual Thuoc Thuoc { get; set; }
        public virtual PhieuDieuTri PhieuDieuTri { get; set; }
    }
}
