//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public Thuoc()
        {
            this.PhieuDieuTri_Thuoc = new HashSet<PhieuDieuTri_Thuoc>();
        }
    
        public int Id { get; set; }
        public string Ma { get; set; }
        public int IdGroup { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public string DonViTinh { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual ICollection<PhieuDieuTri_Thuoc> PhieuDieuTri_Thuoc { get; set; }
        public virtual ThuocGroup ThuocGroup { get; set; }
    }
}
